services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Redirects\:
    resource: '../Classes/*'

  extension.configuration.redirects:
    class: 'array'
    factory:
      - '@TYPO3\CMS\Core\Configuration\ExtensionConfiguration'
      - 'get'
    arguments:
      - 'redirects'

  TYPO3\CMS\Redirects\Report\Status\RedirectStatus:
    public: true

  TYPO3\CMS\Redirects\Hooks\DataHandlerSlugUpdateHook:
    public: true

  TYPO3\CMS\Redirects\Command\CheckIntegrityCommand:
    tags:
      - name: 'console.command'
        command: 'redirects:checkintegrity'
        description: 'Check integrity of redirects'

  TYPO3\CMS\Redirects\Command\CleanupRedirectsCommand:
    tags:
      - name: 'console.command'
        command: 'redirects:cleanup'
        description: 'Cleanup old redirects periodically for given constraints like days, hit count or domains.'

  TYPO3\CMS\Redirects\Configuration\CheckIntegrityConfiguration:
    arguments:
      $extensionConfiguration: '@extension.configuration.redirects'
